### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [rwang430/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by rwang430** [comment]
I think I got it, i added the viewport to the head of the application.html.erb which i googled is supposed to make it mobile friendly. Is this what you mean?

<meta name="viewport" content="width=device-width, initial-scale=1.0">

**Comment by Mikeysax** [comment]
Yes! It makes it work on mobile devices. :+1:
